version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: docker login rckkm $DOCKERHUB_AUTH  
      - run: docker build -t rckkm/rsyslog:alpine ./docker
      - run: docker push rckkm/rsyslog:alpine
