version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          docker login rckkm $DOCKERHUB_AUTH  
          docker build -t rckkm/rsyslog:alpine ./docker
          docker push rckkm/rsyslog:alpine
