version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
              docker build -t dpos-kmv/rsyslog:alpine ./docker
              echo $DOCKERHUB_AUTH | docker login -u $DOCKER_USER --password-stdin
              docker push rckkm/rsyslog:alpine
