version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - run: docker login -u rckkm -p $DOCKERHUB_AUTH  
      - run: docker build -t rckkm/rsyslog:alpine ./docker
      - run: docker push rckkm/rsyslog:alpine
